spring.application.name=climbing.club.manager

# Configuration Spring Mail pour Fake SMTP
spring.mail.host=localhost
spring.mail.port=10025
spring.mail.properties.mail.smtp.auth=false
spring.mail.properties.mail.smtp.starttls.enable=false
