spring.application.name=climbing.club.manager
server.servlet.context-path=/app
app.base-url="http://localhost:8080/app

# Configuration Spring Mail pour Fake SMTP
spring.mail.host=localhost
spring.mail.port=10025
spring.mail.properties.mail.smtp.auth=false
spring.mail.properties.mail.smtp.starttls.enable=false

# Spring MVC
spring.mvc.view.prefix=/WEB-INF/jsp/
spring.mvc.view.suffix=.jsp

# H2 database
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect